services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0.6
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mongo
      - MONGODB_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - type: bind
        source: /tmp/mongo
        target: /data
      - type: bind
        source: ./mongo-admin.sh
        target: /docker-entrypoint-initdb.d/mongo-admin.sh
    restart: unless-stopped
    network_mode: host
  migrations:
    image: migrate/migrate:v4.18.3
    command: '-path=/migrations/ -database mongodb://mongo:mongo@localhost:27017/shop?authSource=admin up'
    network_mode: host
    restart: on-failure:3
    volumes:
      - type: bind
        source: ./migrations
        target: /migrations
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.27.1
    network_mode: host
    restart: unless-stopped
    environment:
      - SWAGGER_JSON=/api/openapi.yml
    volumes:
      - type: bind
        source: ../../api
        target: /api