codecov:
  require_ci_to_pass: false
  
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
    patch: off

ignore:
  - "**/*.gen.go"         # glob accepted
  - cmd/server/*
  - internal/generated/**
  - internal/db/**