codecov:
  require_ci_to_pass: false
  
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
    patch: off

# https://docs.codecov.com/docs/ignoring-paths
# ignore:
#   - "path/to/folder"  # ignore folders and all its contents
#   - "test_*.rb"       # wildcards accepted
#   - "**/*.py"         # glob accepted