version: "2"

run:
  timeout: 30m
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupword
    - err113
    - errchkjson
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - goheader
    - gomodguard
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - misspell
    - mnd
    - nakedret
    - nlreturn
    - paralleltest
    - prealloc
    - tagalign
    - tagliatelle
    - testableexamples
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 120
    exhaustive:
      check:
        - switch
        - map
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    lll:
      line-length: 128
      tab-width: 4
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - .*mock\.go$
      - .*test\.go$
      - .*\.gen\.go$
      - .*\.generated\.go$
      - .*\.pb\.go$
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vrv501/simple-api
  exclusions:
    generated: lax
    paths:
      - .*mock\.go$
      - .*test\.go$
      - .*\.gen\.go$
      - .*\.generated\.go$
      - .*\.pb\.go$ 
      - third_party$
      - builtin$
      - examples$
