version: "2"

run:
  timeout: 30m
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

linters:
  default: none 
  enable:
    - errcheck
    - govet 
    - ineffassign
    - staticcheck
    - unused
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - dupl
    - durationcheck
    - embeddedstructfieldcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - funcorder
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gomoddirectives
    - goprintffuncname
    - gosec 
    - iface
    - intrange
    - lll
    - makezero
    - mirror
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    dupl:
      threshold: 120
    exhaustive:
      check:
        - switch
        - map
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    lll:
      line-length: 128
      tab-width: 4
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - .*mock\.go$
      - .*test\.go$
      - .*\.gen\.go$
      - .*\.generated\.go$
      - .*\.pb\.go$
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vrv501/simple-api
  exclusions:
    generated: lax
    paths:
      - .*mock\.go$
      - .*test\.go$
      - .*\.gen\.go$
      - .*\.generated\.go$
      - .*\.pb\.go$ 
      - third_party$
      - builtin$
      - examples$
